version: '3.8'

services:
  app:
    build: .
    image: ai-router-app:latest
    container_name: ai-router-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MONGODB_URI=${MONGODB_URI}
